### ISSUE TITLE
_Task.Software_module has no value for Prompt

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/nmr-star-dictionary#16]
The prompt shows up at "n/a".

![Screenshot from 2019-03-29 16-51-37](https://user-images.githubusercontent.com/5184895/55264606-f5670780-5242-11e9-8ad2-26ccae097908.png)

**Comment by elulrich** [comment]
Fixed and dictionary update put in git

**Comment by jonwedell** [comment]
Verified.
