### ISSUE TITLE
Can we remove the default value of 'PDB' from _Assembly_db_link.Database_code?

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/nmr-star-dictionary#23]
The reason that I think it might be sensible to do this, is because then I can implement rules that make `_Assembly_db_link.Accession_code` mandatory if they enter a value for `_Assembly_db_link.Database_code`, and I can make `_Assembly_db_link.Database_code` mandatory if they enter a value for `_Assembly_db_link.Accession_code`.

Right now, the first row of the `_Assembly_db_link` loop has `_Assembly_db_link.Database_code` filled in with PDB by default, but they can leave `_Assembly_db_link.Accession_code` blank, which leads to poor quality output. And if the rules are there but 'PDB' is the default value, then `_Assembly_db_link.Accession_code` seems mandatory, unless they delete the default value.

PDB is the first value in the enumeration, so I don't imagine this would cause that much extra work.

**Comment by dmaziuk** [comment]
I suspect this is a hang-up from before joint PDB-BMRB ADIT, it should have been removed long time ago.

One of the things post-processing code does is figuring out the "real data" when making the final entry file. Default values aren't, so this never shows up in the output unless they provided `Accession_code`

**Comment by elulrich** [comment]
Sounds fine. Do I need to update the full dictionary or can you remove the default in your local version and I can do the update later?

**Comment by jonwedell** [comment]
> can you remove the default in your local version and I can do the update later?

This would lead to a merge conflict the next time you attempted to push your local changes to the development branch. If you could update the full dictionary, I would appreciate it.

**Comment by elulrich** [comment]
oops! I have created the dictionary, but have forgotten the three git commands I need to run to commit it.

Help,
Eldon

Also, which subdirectory should I be in?

Is it:

/bmrb_star_v3_files/adit_input

git commit
git pull
git push

I tried git commit from /adit_input and did not get what I expected. Something about already being up to date with the development.

**Comment by jonwedell** [comment]
@elulrich  - Try:

```bash
git commit -a -m '$dictionary_version'
git pull
git push
```

`git commit` will only commit staged changes, of which there are none by default. The `-a` tells git to commit all changes.

**Comment by elulrich** [comment]
I believe PDB had been removed in an update a couple of months ago?

**Comment by jonwedell** [comment]
I don't believe so, I just did a fresh reload and '_Assembly_db_link.Database_code' still has the "default value" set to "PDB".

**Comment by elulrich** [comment]
I believe PDB has been removed as a default.
