### ISSUE TITLE
_Peak_row_format.Position_5 and .Position_uncertainty_5 are missing

### ISSUE THREAD

**Issue by yokochi47** [uwbmrb/nmr-star-dictionary#24]
Hi,
NMR-STAR_internal.doc has _Peak_row_format.Position_5 and _Peak_row_fomar.Position_uncertainty_5, but NMR-STAR.dic does not.

**Comment by kumar-physics** [comment]
Its already fixed in development branch. We will clean up the dev branch and merge with master soon

**Comment by elulrich** [comment]
I believe this problem is fixed.
