### ISSUE TITLE
_Order_param.Model_fit has ? in enumeration

### ISSUE THREAD

**Issue by epeisach** [uwbmrb/nmr-star-dictionary#56]
The enumeration for _Order_param.Model_fit has ? as a possible value.

If you want an open enumeration, I suggest adding _pdbx_item_enumeration_details.closed_flag

**Comment by dmaziuk** [comment]
It may have been a shortcut for completeness check: fields that's enumerated and also nullable. We should remove all dots and question marks from enumerations and see if anything breaks. I expect not, now that ADIT-NMR is going away. Unless (@jonwedell ?) BMRBDep also does it.

**Comment by jonwedell** [comment]
BMRBdep should be fine if you remove enumerations with "?" and "." values. If anything, having those as values is a problem, as it would suggest the null value as an enumeration. This particular tag is not visible in the interface though.

**Comment by elulrich** [comment]
Question mark has been removed from enumerations and the tag enumeration flag is set to open. This will appear in the next dictionary release that is being finalized.
