### ISSUE TITLE
category_group_list is missing definitions for groups that are present...

### ISSUE THREAD

**Issue by epeisach** [uwbmrb/nmr-star-dictionary#63]
The following category groups are referenced in rest of dictionary - but are missing a description.

applied_software
applied_software_history
chem_shift_perturbation
chromatographic_column
chromatographic_system
peak_constraint_links
software_specific_saveframes

**Comment by epeisach** [comment]
nmr_star_val_dict.str  contains the definitions

**Comment by elulrich** [comment]
Fixed in current development dictionary
