### ISSUE TITLE
The tag help box is escaping HTML where it shouldn't - but also some tags need old HTML removed

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/nmr-star-dictionary#9]
- ~~When you click on PubMed ID box under citations.~~
- Hover on molecular assembly. You could not reach the link anyway because you cannot click on that section to bring up the help menu.
- ~~Under the molecular entity section when you click the help or hover on chain identifiers, in the description there’s a \<br>~~.
- The hover over option for molecular entity contains html tags and what appears to be a hyperlink.
- ~~Under molecular entity when you click on Author sequence numbering (sequence code, residue code) there are \<br>’s.~~
- ~~Under molecular entity when you click on Author sequence details there are \<br>’s.~~
- ~~Under ligands, cofactors, etc the PDB section contains html tags.~~
- The hover over the ligands, cofactor, etc. section has html tags and what appears to be a hyperlink.
- ~~The hover over the Chemical shift references has html tags and what appears to be a hyperlink.~~

**Comment by elulrich** [comment]
I believe all of the html has been taken out of the dictionary.

**Comment by jonwedell** [comment]
Verified fixed.
